# Default profiler is lu, but if you are testing everything on localhost, use profile ta
# Default server port is also different
spring:
  profiles:
    active: lu
  data:
    rest:
      basePath: /api/v1

server:
  error:
    whitelabel:
      enabled: false